2020-03-04 03:22:07,352 INFO: Microblog startup [in /home/robbie/Code/Web/flask/microblog/app/__init__.py:54
2020-03-04 03:22:15,046 ERROR: Exception on /edit_profile [POST] [in /home/robbie/Code/Web/flask/microblog/venv/lib/python3.8/site-packages/flask/app.py:1890
Traceback (most recent call last):
  File "/home/robbie/Code/Web/flask/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/robbie/Code/Web/flask/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/robbie/Code/Web/flask/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/robbie/Code/Web/flask/microblog/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/robbie/Code/Web/flask/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/robbie/Code/Web/flask/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/robbie/Code/Web/flask/microblog/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/robbie/Code/Web/flask/microblog/app/routes.py", line 99, in edit_profile
    form = EditProfileForm()
  File "/home/robbie/Code/Web/flask/microblog/venv/lib/python3.8/site-packages/wtforms/form.py", line 212, in __call__
    return type.__call__(cls, *args, **kwargs)
TypeError: __init__() missing 1 required positional argument: 'original_username'
2020-03-04 03:23:47,731 INFO: Microblog startup [in /home/robbie/Code/Web/flask/microblog/app/__init__.py:54
2020-03-04 03:25:16,091 INFO: Microblog startup [in /home/robbie/Code/Web/flask/microblog/app/__init__.py:54
2020-03-05 02:52:54,582 INFO: Microblog startup [in /home/robbie/Code/Web/flask/microblog/app/__init__.py:54
2020-03-05 02:53:17,114 INFO: Microblog startup [in /home/robbie/Code/Web/flask/microblog/app/__init__.py:54
2020-03-05 03:02:55,810 INFO: Microblog startup [in /home/robbie/Code/Web/flask/microblog/app/__init__.py:54
2020-03-05 03:05:45,389 INFO: Microblog startup [in /home/robbie/Code/Web/flask/microblog/app/__init__.py:54
2020-03-05 03:50:54,849 INFO: Microblog startup [in /home/robbie/Code/Web/flask/microblog/app/__init__.py:54
2020-03-05 03:50:59,762 ERROR: Exception on /index [GET] [in /home/robbie/Code/Web/flask/microblog/venv/lib/python3.8/site-packages/flask/app.py:1890
Traceback (most recent call last):
  File "/home/robbie/Code/Web/flask/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/robbie/Code/Web/flask/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/robbie/Code/Web/flask/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/robbie/Code/Web/flask/microblog/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/robbie/Code/Web/flask/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/robbie/Code/Web/flask/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/robbie/Code/Web/flask/microblog/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/robbie/Code/Web/flask/microblog/app/routes.py", line 46, in index
    return render_template('index.html', title='Home Page', form=form, posts=posts)
  File "/home/robbie/Code/Web/flask/microblog/venv/lib/python3.8/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/robbie/Code/Web/flask/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/robbie/Code/Web/flask/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/robbie/Code/Web/flask/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/robbie/Code/Web/flask/microblog/venv/lib/python3.8/site-packages/jinja2/loaders.py", line 129, in load
    code = environment.compile(source, name, filename)
  File "/home/robbie/Code/Web/flask/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "/home/robbie/Code/Web/flask/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/robbie/Code/Web/flask/microblog/venv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/robbie/Code/Web/flask/microblog/app/templates/index.html", line 22, in template
    {% block content %}
jinja2.exceptions.TemplateSyntaxError: Unexpected end of template. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'.
2020-03-05 03:51:36,423 INFO: Microblog startup [in /home/robbie/Code/Web/flask/microblog/app/__init__.py:54
2020-03-05 04:01:46,922 INFO: Microblog startup [in /home/robbie/Code/Web/flask/microblog/app/__init__.py:54
